[package]
name = "osta-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.9"
syn = { version = "2.0.60", features = ["full"] }
proc-macro2 = "1.0.81"

[lib]
proc-macro = true
