[package]
name = "osta-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osta-func = { path = "../osta-func" }
osta-lexer = { path = "../osta-lexer"}
