[package]
name = "osta-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osta-proc-macros = { path = "../osta-proc-macros" }
memmap2 = "0.9.4"
regex = "1.10.4"
